language: node_js

node_js:
  - 'stable'

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

  # Install dotnet cli and add to path
  - export DOTNET_INSTALL_DIR="$HOME/.dotnet"
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 2.0.0 --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

  # Install python3.6
  - curl https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz > Python-3.6.0.tgz
  - tar -zxvf Python-3.6.0.tgz
  - cd Python-3.6.0
  - make
  - make install

install:
  - npm install

script:
  - gulp package
  - gulp upload-vsix
  - npm run lint
  - gulp test

notifications:
  email:
    on_success: never
    on_failure: always
